'use strict';

const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const root = path.join(__dirname, '..');
const read = (rel) => fs.readFileSync(path.join(root, rel), 'utf8');
const bridgeSource = read('clients/windows-px8/ui/bridge.js');
const webSource = read('web/index.html');
const currentVersion = JSON.parse(read('package.json')).version;

function loadBridge() {
  const calls = [];
  const sandbox = {
    URL,
    location: { origin: 'https://triboon.test' },
    console: { log() {}, warn() {}, error() {} },
    setTimeout,
    clearTimeout,
  };
  sandbox.window = sandbox;
  sandbox.__TRIBOON_WINDOWS_BOOTSTRAP__ = {
    chromeVersion: 4,
    playbackCaps: { hevc: true, hwdecRequested: 'd3d11-auto-safe' },
    appVersion: { versionName: currentVersion, versionCode: 0, tv: false, platform: 'windows' },
  };
  sandbox.__TRIBOON_WINDOWS_INVOKE__ = (command, args) => {
    calls.push({ command, args });
    return Promise.resolve(null);
  };
  vm.runInNewContext(bridgeSource, sandbox, { filename: 'bridge.js' });
  return { window: sandbox, calls };
}

test('Windows client: taskbar icon is the mark, not a hard black square', () => {
  const zlib = require('zlib');
  const icon = fs.readFileSync(path.join(root, 'clients/windows-px8/src-tauri/icons/icon.png'));
  assert.strictEqual(icon.subarray(1, 4).toString(), 'PNG');
  assert.strictEqual(icon[25], 6, 'the taskbar PNG must keep an alpha channel');
  let raw = Buffer.alloc(0);
  for (let i = 8; i + 8 <= icon.length; ) {
    const length = icon.readUInt32BE(i);
    const name = icon.subarray(i + 4, i + 8).toString('binary');
    if (name === 'IDAT') raw = Buffer.concat([raw, icon.subarray(i + 8, i + 8 + length)]);
    i += 12 + length;
  }
  const rows = zlib.inflateSync(raw);
  assert.strictEqual(rows[0], 0, 'icon.png is written with filter 0 so corners are readable');
  assert.strictEqual(rows[4], 0, 'the top-left pixel must be transparent, not a black tile');
  const script = read('clients/windows-px8/scripts/punch-taskbar-icon.py');
  assert.match(script, /knock_out|transparent/,
    'the taskbar icon is generated by punching out the black tile');
});

test('Windows client: versions and production identity stay aligned', () => {
  const app = JSON.parse(read('package.json'));
  const client = JSON.parse(read('clients/windows-px8/package.json'));
  const tauri = JSON.parse(read('clients/windows-px8/src-tauri/tauri.conf.json'));
  const cargo = read('clients/windows-px8/src-tauri/Cargo.toml');
  const cargoVersion = /^version\s*=\s*"([^"]+)"/m.exec(cargo);

  assert.strictEqual(client.version, app.version, 'client package version matches Triboon');
  assert.strictEqual(tauri.version, app.version, 'Tauri bundle version matches Triboon');
  assert.strictEqual(cargoVersion && cargoVersion[1], app.version, 'Rust package version matches Triboon');
  assert.strictEqual(tauri.productName, 'Triboon');
  assert.strictEqual(tauri.identifier, 'app.triboon.windows', 'production id cannot reuse the PX8 preview id');
  assert.deepStrictEqual(tauri.bundle.targets, ['nsis'], 'the public Windows client is an NSIS installer');
});

test('Windows client: remote WebView gets only the guarded Triboon bridge', () => {
  const tauri = JSON.parse(read('clients/windows-px8/src-tauri/tauri.conf.json'));
  const main = read('clients/windows-px8/src-tauri/src/main.rs');
  const capabilities = ['connect', 'catalog', 'player'].map((name) =>
    JSON.parse(read(`clients/windows-px8/src-tauri/capabilities/${name}.json`)));
  const catalog = capabilities.find((capability) => capability.identifier === 'trusted-remote-catalog');

  assert.strictEqual(tauri.app.withGlobalTauri, false, 'general Tauri globals stay disabled');
  assert.ok(tauri.app.security.csp, 'the bundled connect/player pages have a CSP');
  assert.match(tauri.app.security.csp, /object-src 'none'/);
  assert.ok(catalog && catalog.local === false, 'the remote catalog has its own non-local capability');
  assert.deepStrictEqual(catalog.remote.urls, ['http://*:*', 'https://*:*'],
    'remote ACL includes Triboon custom ports such as 7777 and 8443');
  for (const remote of ['http://triboon.local:7777/', 'https://media.example:8443/']) {
    assert.ok(catalog.remote.urls.some((pattern) => new URLPattern(pattern).test(remote)),
      `remote ACL matches ${remote}`);
  }
  for (const capability of capabilities) {
    assert.ok(Array.isArray(capability.permissions));
    for (const permission of capability.permissions) {
      assert.doesNotMatch(permission, /^(?:core:default|shell|fs|process|clipboard|http):?/i,
        'no window has a broad default, shell, filesystem, process, clipboard, or HTTP capability');
    }
  }
  assert.match(main, /fn origin_from_page_url/,
    'catalog origin checks ignore hash routes such as #/home');
  assert.match(main, /navigation_allowed[\s\S]+origin_from_page_url\(raw\)/,
    'navigation is constrained to the configured exact origin');
  assert.match(main, /let current = origin_from_page_url\(current\.as_str\(\)\)/,
    'Play is allowed on hash-routed catalog pages such as #/home');
  assert.match(main, /require_catalog_origin[\s\S]+require_player_or_catalog/,
    'native commands revalidate the caller instead of trusting JavaScript');
  assert.match(main, /include_str!\("\.\.\/\.\.\/ui\/bridge\.js"\)/,
    'the reviewed bridge is the code injected into the catalog');
  assert.match(main, /if trusted[\s\S]+webview\.eval\(bridge_script\(\)\)/,
    'bridge injection happens only after the configured origin check');
});

test('Windows client: in-app update uses official installers only', () => {
  const main = read('clients/windows-px8/src-tauri/src/main.rs');
  const update = read('clients/windows-px8/src-tauri/src/update.rs');
  const catalog = JSON.parse(read('clients/windows-px8/src-tauri/capabilities/catalog.json'));
  const connect = JSON.parse(read('clients/windows-px8/src-tauri/capabilities/connect.json'));
  assert.ok(catalog.permissions.includes('allow-windows-install-app-update'),
    'the catalog capability must allow the update command');
  assert.ok(!connect.permissions.includes('allow-windows-install-app-update'),
    'the connect screen must not install updates');
  assert.match(main, /fn windows_install_app_update[\s\S]+require_catalog_origin[\s\S]+allowed_windows_update_filename/,
    'Rust re-checks catalog origin and the official installer URL');
  assert.match(update, /\/d1same\/triboon\/releases\/latest\/download\/Triboon-Windows-Client\.exe/,
    'only the stable Windows client alias is accepted');
  assert.match(update, /\/d1same\/triboon\/releases\/latest\/download\/Triboon-Windows-Server\.exe/,
    'only the stable Windows server alias is accepted');
  assert.match(update, /SHA256SUMS\.txt/,
    'the downloaded installer must match the official checksum file');
  assert.doesNotMatch(update, /\/S"|\/SILENT|\/VERYSILENT/,
    'Windows updates must open the installer UI, not a silent install');
  assert.match(webSource, /function openWindowsUpdate\([\s\S]+installAppUpdate[\s\S]+WIN_CLIENT_URL/,
    'the catalog uses the Windows installer path instead of the APK');
  assert.match(webSource, /body\.windowsDesktop #apkUpdate/,
    'the Windows desktop client hides the Android APK button');
});

test('Windows client: a saved server reconnects without another click', () => {
  const connect = read('clients/windows-px8/ui/connect.html');
  assert.match(connect, /invoke\('last_server'\)[\s\S]+form\.requestSubmit\(\)/,
    'the local connect screen should immediately reopen a previously verified server');
});

test('Windows client: bridge exposes Android-compatible native playback controls', () => {
  const { window, calls } = loadBridge();
  const bridge = window.TriboonTV;
  const required = [
    'nativeChromeVersion', 'nativePlaybackCaps', 'appVersion', 'installAppUpdate', 'showVideoLoading', 'playVideo', 'playLive',
    'closeVideo', 'play', 'pause', 'resume', 'togglePlay', 'seekTo', 'seekBy', 'nextEpisode',
    'selectQuality', 'selectAudio', 'selectSubtitle', 'updateSubtitleChoices',
    'updateActiveSubtitle', 'updateVideoDuration', 'updateEpisodeChoices', 'upNext',
    'upNextHide', 'setLiveFav', 'setLiveEpg', 'openGuide', 'closeGuide', 'setGuidePipRect',
  ];
  for (const name of required) assert.strictEqual(typeof bridge[name], 'function', `${name} is exposed`);
  assert.ok(bridge.nativeChromeVersion() >= 1, 'native handoff is enabled');

  const caps = JSON.parse(bridge.nativePlaybackCaps());
  assert.strictEqual(caps.player, 'libmpv');
  assert.strictEqual(caps.hwdecRequested, 'd3d11-auto-safe');
  assert.strictEqual(caps.softwareFallback, true);
  assert.deepStrictEqual(JSON.parse(bridge.appVersion()), {
    versionName: currentVersion,
    versionCode: 0,
    tv: false,
    platform: 'windows',
  }, 'the existing Rust bootstrap version is exposed through the narrow bridge');

  assert.strictEqual(bridge.playVideo(JSON.stringify({
    url: '/api/stream/movie?t=secret', playbackToken: 91, start: 12,
  })), true);
  assert.strictEqual(calls.at(-1).command, 'windows_player_play_vod');
  assert.strictEqual(calls.at(-1).args.payload.playbackToken, 91);
  assert.strictEqual(bridge.installAppUpdate(
    'https://github.com/d1same/triboon/releases/latest/download/Triboon-Windows-Client.exe',
  ), true);
  assert.strictEqual(calls.at(-1).command, 'windows_install_app_update');
  assert.strictEqual(
    calls.at(-1).args.url,
    'https://github.com/d1same/triboon/releases/latest/download/Triboon-Windows-Client.exe',
  );

  assert.throws(() => bridge.playVideo(JSON.stringify({
    url: 'https://evil.example/movie?t=secret', playbackToken: 91,
  })), /invalid/i, 'VOD URLs cannot escape the configured server origin');

  bridge.seekTo(44);
  assert.deepStrictEqual(
    JSON.parse(JSON.stringify(calls.at(-1))),
    { command: 'windows_player_control', args: { action: 'seek_absolute', payload: { seconds: 44 } } },
  );
  bridge.seekBy(-20);
  assert.deepStrictEqual(
    JSON.parse(JSON.stringify(calls.at(-1))),
    { command: 'windows_player_control', args: { action: 'seek_relative', payload: { seconds: -20 } } },
  );
});

test('Windows client: live player chrome matches the Live TV page, not an empty PiP', () => {
  const css = read('clients/windows-px8/ui/player.css');
  const js = read('clients/windows-px8/ui/player.js');
  assert.match(webSource, /function windowsDesktopLiveWatchFromGuide\(\) \{[\s\S]+__triboonWindowsBridge === true/,
    'only the Windows catalog bridge leaves the guide after a channel pick');
  assert.match(webSource, /if \(windowsDesktopLiveWatchFromGuide\(\)\) closePlayerGuide\(\);/,
    'picking a channel from the in-player guide opens the same full live player as the Live TV page');
  assert.match(js, /\$\('captions'\)\.hidden = state\.mode === 'live'/,
    'live chrome hides CC like the web Live TV player');
  assert.match(css, /body\.live #captions,[\s\S]+body\.live #audio,[\s\S]+body\.live #quality/,
    'live CSS hides CC/audio/quality, same as web #player.live');
  assert.match(js, /\$\('guide'\)\.hidden = false/,
    'Guide stays on the live control bar');
  assert.match(js, /\$\('favorite'\)\.hidden = state\.mode !== 'live'/,
    'Favorite stays on the live control bar');
  assert.match(js, /function sessionMode\(session, current\) \{[\s\S]+isLive !== undefined[\s\S]+'vod'/,
    'a movie after Live TV must leave live chrome so the seek bar comes back');
  assert.match(js, /case 'closed':[\s\S]+state\.mode = 'vod'/,
    'closing the player drops leftover IPTV chrome before the next VOD');
  const boolFn = js.match(/function bool\(value, fallback\) \{[\s\S]*?\n  \}/)[0];
  const modeFn = js.match(/function sessionMode\(session, current\) \{[\s\S]*?\n  \}/)[0];
  const sessionMode = new Function(`${boolFn}\n${modeFn}\nreturn sessionMode;`)();
  assert.strictEqual(sessionMode({ isLive: false }, 'live'), 'vod',
    'Iran International leftover live chrome must not hide the movie seek bar');
  assert.strictEqual(sessionMode({ isLive: true }, 'vod'), 'live');
  assert.strictEqual(sessionMode({}, 'live'), 'live',
    'a slim live progress event without isLive keeps Live TV chrome');
  const rust = read('clients/windows-px8/src-tauri/src/player.rs');
  assert.match(rust, /windows_player_play_live[\s\S]+if request\.guide \{[\s\S]+request\.guide = false;[\s\S]+__tvNativeGuideClosed/,
    'a guide channel pick must not start a chrome-less live session');
});

test('Windows client: VOD fullscreen does not reopen leftover guide PiP', () => {
  const rust = read('clients/windows-px8/src-tauri/src/player.rs');
  const js = read('clients/windows-px8/ui/player.js');
  assert.match(rust, /fn show_player\([\s\S]+clear_guide_pip\(app\);[\s\S]+restore_windowed_player[\s\S]+player\.show\(\)[\s\S]+main\.hide\(\)/,
    'Play covers the catalog window first, then hides it, so the desktop does not flash');
  assert.match(rust, /\.transparent\(true\)/,
    'the player window stays transparent so libmpv video shows through the WebView');
  const css = read('clients/windows-px8/ui/player.css');
  assert.match(css, /html, body \{[^}]*background: transparent/,
    'playing chrome must not paint an opaque body over the video');
  assert.match(css, /body\[data-state="loading"\],[\s\S]+body\[data-state="error"\] \{ background: #000; \}/,
    'the loader stays black so Play does not flash the wallpaper');
  assert.match(rust, /fn toggle_player_fullscreen\([\s\S]+if stored_guide_pip\(app\)\.is_some\(\) \{[\s\S]+set_fullscreen\(true\)/,
    'the fullscreen button leaves guide PiP into exclusive fullscreen, it does not restore the leftover slot');
  assert.match(rust, /fn leave_guide_mode\([\s\S]+restore_windowed_player/,
    'closing the guide returns to a windowed player, not automatic exclusive fullscreen');
  assert.match(js, /if \(document\.body\.classList\.contains\('guide-pip'\)\) \{\s*expandGuidePip\(\);/,
    'the fullscreen icon expands guide PiP instead of shrinking the live player');
  assert.match(js, /function canHideControls\(\) \{[\s\S]+state\.playback === 'ready'/,
    'ready video hides chrome the same way playing does');
  assert.match(js, /if \(value === state\.playback\) return;/,
    'progress ticks must not restart the chrome hide timer');
  assert.match(js, /if \(!document\.body\.classList\.contains\('controls-hidden'\)\) return;[\s\S]+if \(Math\.abs\(x - lastMouseX\) < 24 && Math\.abs\(y - lastMouseY\) < 24\) return;/,
    'mouse jitter cannot keep chrome up; a real move after hide brings it back');
  assert.match(css, /body\.controls-hidden \{ cursor: none; \}/,
    'hidden fullscreen chrome also hides the cursor');
  assert.match(js, /case 'progress':[\s\S]+data\.playing !== false && !data\.paused && !data\.buffering[\s\S]+setPlayback\('playing'\)/,
    'progress ticks keep the playing state without treating every second as a fresh start');
  assert.match(js, /if \(value === state\.playback\) return;[\s\S]+scheduleHide\(\)/,
    'progress while the picture is up hides chrome even if ready never arrived first');
  assert.match(rust, /session\.ui\.event_type = if session\.ui\.playing \{[\s\S]+"playing"\.into\(\)[\s\S]+"ready"\.into\(\)/,
    'first decoded frame publishes playing so the overlay can hide');
  assert.match(rust, /show_catalog\(app\);[\s\S]+__tvNativeVideoClosed/,
    'Windows shows the catalog before the close checkpoint so hidden WebView2 cannot drop saveWatch');
});

test('Windows client: Live TV guide PiP docks to the slot and can return to full screen', () => {
  const html = read('clients/windows-px8/ui/player.html');
  const css = read('clients/windows-px8/ui/player.css');
  const js = read('clients/windows-px8/ui/player.js');
  const rust = read('clients/windows-px8/src-tauri/src/player.rs');
  const main = read('clients/windows-px8/src-tauri/src/main.rs');
  assert.match(webSource, /function syncNativeGuidePipRect\(\) \{[\s\S]+vw: window\.innerWidth[\s\S]+vh: window\.innerHeight/,
    'catalog still tells native the slot size and the page size for DPI scaling');
  assert.match(webSource, /if \(S\.nativeGuideMode\) scheduleNativeGuidePipSync\(\);/,
    'moving or resizing the catalog window re-syncs the PiP slot');
  assert.match(webSource, /S\._pipSyncT2 = setTimeout\(syncNativeGuidePipRect, 260\)/,
    'PiP sync retries after Windows leaves fullscreen');
  assert.match(rust, /fn scale_guide_rect\(/,
    'native PiP math is a testable helper, not an untested window move');
  assert.match(rust, /fn default_slot\(/,
    'opening the guide parks the player in the top-left slot before JS measures');
  assert.doesNotMatch(rust, /payload\.width < 240\.0/,
    'a real guide slot smaller than 240px must still be accepted');
  assert.match(rust, /eval_callback\(&app, "__tvNativeGuideClosed"/,
    'leaving PiP tells the catalog to close the guide, like Android');
  assert.match(main, /WindowEvent::Moved\(_\) \| tauri::WindowEvent::Resized\(_\)/,
    'dragging the catalog window keeps the mini player in the slot');
  assert.match(html, /id="pipExpand"[\s\S]+Full screen/,
    'PiP has a visible Full screen control');
  assert.match(css, /body\.guide-pip \.pip-expand \{ display: inline-flex; \}/,
    'the Full screen chip is shown only while the mini player is docked');
  assert.match(js, /windows_player_close_guide/,
    'Full screen / click on the mini player returns to the live player with controls');
});

test('Windows client: Guide opens Live TV, not leftover episodes', () => {
  const html = read('clients/windows-px8/ui/player.html');
  const css = read('clients/windows-px8/ui/player.css');
  const js = read('clients/windows-px8/ui/player.js');
  const guideIcon = html.slice(html.indexOf('id="i-guide"'), html.indexOf('</symbol>', html.indexOf('id="i-guide"')));
  const listIcon = html.slice(html.indexOf('id="i-list"'), html.indexOf('</symbol>', html.indexOf('id="i-list"')));
  assert.match(guideIcon, /m16 12 5 3-5 3v-6Z/,
    'Guide keeps the same list+play glyph as the web #chGuide button');
  assert.doesNotMatch(listIcon, /m16 12 5 3-5 3v-6Z/,
    'Episodes must not reuse the IPTV Guide icon');
  assert.match(js, /\$\('guide'\)\.hidden = false/,
    'Guide stays visible on movies and shows, matching desktop web and Android');
  assert.match(js, /\$\('episodes'\)\.hidden = state\.mode === 'live' \|\| !state\.episodeChoices\.length/,
    'Live TV must not keep a leftover episode picker');
  assert.match(js, /if \(state\.mode === 'live'\) \{\s*state\.episodeChoices = \[\];/,
    'switching to a live channel clears the previous show episode list');
  assert.match(js, /else if \(key === 'g'\) \{ event\.preventDefault\(\); \$\('guide'\)\.click\(\); \}/,
    'G opens the TV guide on both live and VOD, like the desktop web player');
  assert.match(css, /body\.live #episodes/,
    'live CSS hides the episode button even if leftover choices arrive');
  assert.match(webSource, /async function togglePlayerGuide\(\) \{[\s\S]+closePlayerEpisodes\(\);[\s\S]+rememberVodReturn\(\)/,
    'opening the shared guide closes the episode strip on every client');
});

test('Windows client: Cast button uses the shared Google Cast picker', () => {
  const html = read('clients/windows-px8/ui/player.html');
  const js = read('clients/windows-px8/ui/player.js');
  const rust = read('clients/windows-px8/src-tauri/src/player.rs');
  assert.match(html, /id="cast"[\s\S]+Cast to TV/,
    'native chrome has the same Cast control as the web player');
  assert.match(js, /\$\('cast'\)\.hidden = state\.mode === 'live'/,
    'Cast stays off Live TV, same as web');
  assert.match(js, /\$\('cast'\)\.addEventListener\('click', \(\) => send\('cast'\)\)/,
    'the Cast button asks the catalog to open the device picker');
  assert.match(rust, /"cast" \| "start_cast" => Ok\(ControlAction::Cast\)/,
    'cast is a typed native control');
  assert.match(rust, /ControlAction::Cast => \{\s*eval_callback\(&app, "__tvNativeCastStart"/,
    'Windows Cast reaches the same catalog picker as the web player');
});

test('Windows client: windowed play keeps the OS title bar and matches web OSD', () => {
  const html = read('clients/windows-px8/ui/player.html');
  const css = read('clients/windows-px8/ui/player.css');
  const js = read('clients/windows-px8/ui/player.js');
  const rust = read('clients/windows-px8/src-tauri/src/player.rs');
  assert.match(rust, /\.decorations\(true\)/,
    'the player window uses the Windows title bar so it can be moved while a movie plays');
  assert.match(rust, /fn restore_windowed_player\([\s\S]+set_decorations\(true\)/,
    'leaving fullscreen puts the Windows title bar back');
  assert.match(rust, /fn apply_stored_guide_pip\([\s\S]+set_decorations\(false\)/,
    'guide PiP stays chrome-less so the slot is only the picture');
  assert.doesNotMatch(html, /id="gpuBadge"|id="centerPlay"|GPU checking/,
    'native overlay must not show a GPU/video-card badge or a center pause circle');
  assert.doesNotMatch(css, /center-play|gpu-badge/,
    'pause state uses the bottom play button, not a middle circle');
  assert.match(html, /id="playerBack"[\s\S]+id="qualityPill"[\s\S]+id="clockNow"[\s\S]+id="endsAt"/,
    'native OSD keeps the web back button, quality pill, and clock');
  assert.match(css, /\.playerMetaQuality \{/,
    'quality is a web-style pill, not a verified or GPU chip');
  assert.match(js, /function updateQualityPill\(\) \{[\s\S]+verified\|gpu\|video\\s\*card/,
    'verified / GPU / video-card labels stay off the overlay');
  assert.doesNotMatch(js, /gpuBadge|centerPlay|updateGpu/,
    'GPU proof stays in the details panel, not on the movie');
});

test('Windows client: native chrome matches the web player loader and transport', () => {
  const html = read('clients/windows-px8/ui/player.html');
  const css = read('clients/windows-px8/ui/player.css');
  const js = read('clients/windows-px8/ui/player.js');
  const rust = read('clients/windows-px8/src-tauri/src/player.rs');
  assert.match(html, /class="loadSteps"[\s\S]+id="loadingStage"/,
    'startup uses the web load bar, not a spinning ring');
  assert.match(html, /src="triboon.png"/, 'startup shows the Triboon wordmark');
  assert.match(html, /id="i-back"[\s\S]+M3 2v6h6[\s\S]+id="i-forward"[\s\S]+M21 2v6h-6/,
    'skip icons are the same stroke arrows as the web player');
  assert.doesNotMatch(html, /<text[^>]*>10<\/text>|<text[^>]*>30<\/text>/,
    'skip icons must not stamp 10/30 inside the glyph');
  assert.match(html, /class="seekLine"[\s\S]+id="currentTime"[\s\S]+id="timeline"[\s\S]+id="duration"/,
    'seek times sit on the sides of the bar like web');
  assert.match(css, /body\[data-state="loading"\] \.loading/,
    'the solid loader only covers startup');
  assert.doesNotMatch(css, /data-state="buffering"\] \.loading/,
    'mid-play cache pauses must not flash the full-page loader');
  assert.match(css, /\.control\.primary \{ width: 58px; height: 58px; background: rgba\(5,3,9,\.4\)/,
    'play is a dark web-style circle, not a white Windows button');
  assert.match(js, /PLAYER_LOADING_STAGES = \['Preparing', 'Finding source', 'Mounting', 'Checking health\.\.\.', 'Starting stream'\]/,
    'Windows startup stages match the web player');
  assert.match(js, /if \(hot\) \{[\s\S]+setLoadingStage\(2\);[\s\S]+\[500, 1100\][\s\S]+\[650, 1400, 2200, 3000\]/,
    'Windows uses the same cold and hot stage timing as web');
  assert.match(js, /if \(loadingStarted\) return;/,
    'loading status text does not restart on every session event');
  assert.match(js, /if \(\(value === 'paused' \|\| value === 'ready'\) && !sawFirstFrame\) return;/,
    'ready or paused before the first picture must not hide or restart the load lane');
  assert.match(css, /\.loading \{[^}]*opacity: 0;[^}]*visibility: hidden/,
    'hiding the loader must not remount the 1.35s lane with display:none');
  assert.match(css, /animation: loadLane 1\.35s ease-in-out infinite/,
    'the startup lane uses the same 1.35s sweep as web');
  assert.match(rust, /struct LoadingPayload \{[\s\S]+playback_token: u64,[\s\S]+hot: bool,/,
    'Windows inherits the web hot-join flag so a prepared Play does not restart at Finding source');
  assert.match(js, /if \(value === 'buffering' && sawFirstFrame\)/,
    'after the first frame, buffering does not replace the picture with the loader');
  assert.match(js, /function overlaySourceLine\(\) \{[\s\S]+looksLikeFilename\(state\.source\)/,
    'native overlay hides .mkv filenames and keeps title plus episode');
  assert.match(css, /--buffer,0%/,
    'buffer and played share the same slider track so they stay aligned');
  assert.match(js, /setProperty\('--buffer'/,
    'buffer width is painted on the same track as the orange progress');
});

test('Windows client: About and seek stay on the shared web player contract', () => {
  const { window } = loadBridge();
  const playerHtml = read('clients/windows-px8/ui/player.html');
  assert.match(webSource, /id="aboutBtn"[\s\S]+id="playerAbout"[\s\S]+function openPlayerAbout\(\)/,
    'Windows catalog WebView uses the same in-player About card as browser and Android web');
  assert.match(webSource, /function nudgeSeek\(delta\)/,
    'Windows catalog seeks use the same nudgeSeek path as web and Android stress');
  assert.match(webSource, /window\.TriboonTV\.showTitleInfo/,
    'native About handoff is the Android/Windows showTitleInfo bridge');
  assert.match(playerHtml, /id="back"[\s\S]+id="forward"/,
    'Windows native chrome still has back/forth skip buttons');
  assert.strictEqual(typeof window.TriboonTV.showTitleInfo, 'undefined',
    'Windows native About handoff is not on the bridge yet; catalog WebView About is the current contract');
});

test('Windows client: web telemetry identifies libmpv and reports the desktop version', () => {
  assert.match(webSource,
    /function nativePlayerTelemetryId\(\)[\s\S]+caps && caps\.player[\s\S]+player === 'libmpv'[\s\S]+return 'libmpv'/,
    'native telemetry uses the native capability player identity');
  assert.match(webSource,
    /__triboonWindowsBridge === true\) return 'libmpv'/,
    'the reviewed Windows bridge identity is a safe fallback');
  assert.match(webSource, /if \(p\.usingNative\) return nativePlayerModeLabel\(\)/,
    'the support mode label is platform-aware');
  assert.match(webSource, /player: p\.usingNative \? nativePlayerTelemetryId\(\) : 'web'/,
    'activity rows distinguish libmpv from ExoPlayer');
  assert.match(webSource, /app\.platform === 'windows'[\s\S]+Windows/,
    'client version labels identify the Windows desktop client');
});

test('Windows client: native events preserve playback identity and full lifecycle', () => {
  const { window } = loadBridge();
  const seen = [];
  const callbacks = [
    '__tvNativePlaybackSurfaceReady', '__tvNativeVideoReady', '__tvNativeVideoPlaying',
    '__tvNativeVideoPaused', '__tvNativeVideoProgress', '__tvNativeVideoStats',
    '__tvNativeVideoSeek', '__tvNativeVideoEnded', '__tvNativeVideoClosed',
    '__tvNativeVideoError', '__tvNativeVideoNext', '__tvNativeLiveReady',
    '__tvNativeLiveClosed', '__tvNativeLiveError', '__tvNativeLiveGuide', '__tvNativeLiveZap',
  ];
  for (const name of callbacks) window[name] = (...args) => seen.push([name, args]);

  window.__triboonWindowsPlayerEvent({ type: 'ready', position: 9, duration: 100, playbackToken: 73 });
  window.__triboonWindowsPlayerEvent({ type: 'progress', position: 10, duration: 100, playbackToken: 73 });
  window.__triboonWindowsPlayerEvent({ type: 'closed', position: 11, duration: 100, playbackToken: 73 });
  assert.deepStrictEqual(JSON.parse(JSON.stringify(seen)), [
    ['__tvNativeVideoReady', [9, 100, 73]],
    ['__tvNativeVideoProgress', [10, 100, 73]],
    ['__tvNativeVideoClosed', [11, 100, false, 73]],
  ]);

  for (const callback of callbacks) {
    assert.match(bridgeSource, new RegExp(callback), `${callback} is routed by the bridge`);
  }
});

test('Windows client: Rust owns a persistent, observable D3D11/libmpv player', () => {
  const main = read('clients/windows-px8/src-tauri/src/main.rs');
  const player = read('clients/windows-px8/src-tauri/src/player.rs');
  const playerUi = read('clients/windows-px8/ui/player.js');

  for (const command of [
    'windows_player_show_loading', 'windows_player_play_vod', 'windows_player_play_live',
    'windows_player_control', 'windows_player_update', 'windows_player_open_guide',
    'windows_player_close_guide', 'windows_player_set_guide_pip_rect',
  ]) {
    assert.match(main, new RegExp(`player::${command}`), `${command} is registered`);
    assert.match(player, new RegExp(`(?:fn|pub fn) ${command}`), `${command} is implemented`);
  }

  assert.match(player, /hwdec["']?\s*,\s*["']auto-safe|auto-safe[\s\S]+hwdec/i,
    'hardware decode uses the safe automatic path');
  assert.match(player, /d3d11/i, 'Windows rendering selects D3D11');
  assert.match(player, /hwdec-current/i, 'runtime hardware decoder state is observed');
  assert.match(player, /"audioId": ui\.audio_id/, 'runtime stats expose the selected audio track');
  assert.match(player, /fn mpv_alang\(pref: &str\) -> String \{[\s\S]{0,200}"eng,en"/,
    'Windows libmpv prefers English audio unless the payload asks for another language');
  assert.match(player, /mpv\.set_property\("alang", mpv_alang\(&session\.preferred_audio_language\)/,
    'ITA.ENG files start on English because load_session sets mpv alang');
  assert.match(player, /time-pos/i, 'native progress uses mpv playback time');
  assert.doesNotMatch(player, /last_position = session\.last_duration/,
    'a mid-title remux EOF must not teleport Windows progress to duration');
  assert.match(player, /demuxer-cache|cache-duration|paused-for-cache/i, 'buffering is observable');
  assert.match(player, /playback_token|playbackToken/i, 'events carry playback identity');
  assert.match(player, /redact|query\(|split\('\?'\)|set_query\(None\)/i,
    'native errors/logs have a URL-token redaction path');
  assert.match(playerUi, /ArrowLeft|ArrowRight|MediaPlayPause|fullscreen/i,
    'native chrome handles keyboard/media/fullscreen controls');
  assert.match(player, /if let Some\(error\) = event_error \{[\s\S]+SessionMode::Live && try_live_fallback[\s\S]+native media error/,
    'Raw(-16) / nothing-to-play on HLS must try the server remux before the error dialog');
});

test('Windows client: Up Next is a small Next chip plus X', () => {
  const html = read('clients/windows-px8/ui/player.html');
  const css = read('clients/windows-px8/ui/player.css');
  const js = read('clients/windows-px8/ui/player.js');
  const rust = read('clients/windows-px8/src-tauri/src/player.rs');
  assert.match(html, /id="upNextPlay"[\s\S]+>\s*Next Episode\s*<[\s\S]+id="upNextDismiss"/,
    'Windows Up Next is a Next Episode chip plus dismiss, not a title card');
  assert.doesNotMatch(html, /id="upNextTitle"|id="upNextSub"|id="upNextProgress"|up-next-kicker/,
    'Windows Up Next must not show a title, still, or kicker');
  assert.match(css, /\.up-next-play \{ --un-cd: 0%; width: auto; padding: 0 16px/,
    'Windows Next is a small pill, not a wide card');
  assert.match(css, /\.up-next-dismiss \{ width: 36px/,
    'Windows dismiss matches the Next chip height');
  assert.match(js, /\$\('upNextPlay'\)\.addEventListener\('click', \(\) => send\('next'\)\);[\s\S]+\$\('upNextDismiss'\)\.addEventListener\('click', \(\) => send\('up_next_dismiss'\)\);/,
    'Play starts the next episode and X dismisses without starting it');
  assert.match(js, /function handleUpNextKey\(event\) \{[\s\S]+upNextVisible\(\)[\s\S]+ArrowLeft[\s\S]+upNextPlay[\s\S]+ArrowRight[\s\S]+upNextDismiss[\s\S]+Enter[\s\S]+upNextPlay'\)\)\.click\(\)/,
    'Windows keyboard Left/Right chooses Next/X and Enter activates');
  assert.match(js, /if \(upNextVisible\(\)\) \{ \$\('upNextDismiss'\)\.click\(\); return; \}/,
    'Windows Back dismisses Next Episode instead of closing the player');
  assert.match(css, /\.up-next \{[^}]*z-index: 19/,
    'Windows Next chip sits above the control bar so clicks reach it');
  assert.match(rust, /"up_next_dismiss" \| "dismiss_up_next" => Ok\(ControlAction::UpNextDismiss\)/,
    'dismiss reaches the web owner through a typed control');
  assert.match(rust, /ControlAction::UpNextDismiss => eval_callback\(app, "__upNextDismissNative", vec!\[\]\)/,
    'Windows dismiss calls the same web dismiss hook as Android');
});

test('Windows client: LGPL runtime and honest hardware verification are documented', () => {
  const readme = read('clients/windows-px8/README.md');
  const source = read('clients/windows-px8/LIBMPV-SOURCE.md');
  const license = read('clients/windows-px8/LIBMPV-LICENSE.LGPL');
  const verify = read('VERIFY.md');
  const notices = read('THIRD-PARTY-NOTICES.md');

  for (const doc of [readme, verify]) {
    assert.match(doc, /hwdec-current/i, 'GPU proof uses runtime decoder state');
    assert.match(doc, /software\s+fallback|falls?\s+back\s+to\s+software/i,
      'unsupported hardware decode has a safe fallback');
  }
  assert.match(source, /f4d13e1c2c91f3a56e589aef9cb44cbc02e26e47/);
  assert.match(source, /a237017af09e72a689882afdf0adf6108c33c0fd/);
  assert.match(source, /20dffed429610b52dbb9e3d5b4124145b2a954ef3e6e8fe319cc249a5a794c51/);
  assert.match(source, /replace|replacement/i);
  assert.match(license, /GNU LESSER GENERAL PUBLIC LICENSE[\s\S]+Version 2\.1/);
  assert.match(notices, /dynamically loads `libmpv-2\.dll`/);
  assert.doesNotMatch(readme, /Dolby Vision[^\n]+guarantee/i,
    'hardware-chain-dependent Dolby Vision is not promised universally');
});
